name: MCP Integration Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-mcp-integration:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g @modelcontextprotocol/server-github
        
    - name: Test MCP Configuration
      run: |
        echo "Testing MCP server configuration..."
        echo "GitHub token available: ${{ secrets.GITHUB_TOKEN != '' }}"
        
    - name: Create test issue
      if: github.event_name == 'push'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'MCP Integration Test',
            body: 'This issue was created automatically to test MCP integration with the T-Watch project.',
            labels: ['mcp-test', 'automation']
          })
          
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ MCP integration test passed! This PR is ready for review.'
          }) 